---
title: "GO enrichment analysis"
output: html_document
date: "2024-04-26"
---

```{r, echo=F, warning=F, message=F}
rm(list=ls())
set.seed(123)
knitr::opts_chunk$set(autodep = TRUE)
library(knitr)
library(RSQLite)
#install.packages("vctrs")
library(vctrs)
library(dplyr)
library(knitr)
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, 
                      message = FALSE, cache.lazy = FALSE) # avoid error of long vectors https://stackoverflow.com/questions/39417003/long-vectors-not-supported-yet-error-in-rmd-but-not-in-r-script 
library(kableExtra)
library(RColorBrewer)
library(gplots)
library(tidyverse)
library(gridExtra)
library(ggpubr)
#library(DT)

#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("GO.db")
library(GO.db)

#install.packages('BiocManager')
library(BiocManager)

#install.packages(c("matrixStats", "Hmisc", "splines", "foreach", "doParallel", "fastcluster", "dynamicTreeCut", "survival"))

#install.packages("htmltools")
#remotes::install_github("rstudio/htmltools")
library(htmltools)

#install package impute 
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("impute")
library(impute)

# install package preprocessCore
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("preprocessCore")
library(preprocessCore)

library(WGCNA)


#install_github("jdstorey/qvalue")   # install qvalue package 
#library(qvalue)
#library("devtools")
#install.packages("Rtools")
#install_github('xinhe-lab/mirage')
library(mirage)
library(igraph)

#detach(package:dequer,unload=TRUE)
```






```{r, echo=F, message=F, warning=F, results=F, eval=F}
######## replicating the results 
###https://github.com/linnykos/covarianceSelection
# install dependent packages 

#install.packages("doMC", repos="http://R-Forge.R-project.org")
library("doMC")

# if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("org.Hs.eg.db")
library("org.Hs.eg.db") # Genome wide annotation for Human https://bioconductor.org/packages/release/data/annotation/html/org.Hs.eg.db.html



library("devtools")
devtools::install_github("linnylin92/covarianceSelection", subdir = "covarianceSelection")

```



```{r, echo=F, message=F, warning=F}
#https://biostatsquid.com/volcano-plots-r-tutorial/
library(ggrepel) # for nice annotations

go_enrichment=data.frame(terms=c("cell-cell signaling involved in cardiac conduction (GO:0086019)
", "cell communication involved in cardiac conduction (GO:0086065)
", "monoatomic ion channel complex (GO:0034702)
", "transmembrane transporter complex (GO:1902495)", "transporter complex (GO:1990351)"), fold_change=c(63.56, 39.91, 18.26, 13.69, 13.41), pvalue=c(0.00401, 0.0274, 0.000389, 0.00207, 0.00234))

ggplot(data = go_enrichment, aes(x = log2(fold_change), y = -log10(pvalue), label = terms)) +
  geom_hline(yintercept = -log10(0.05), col = "red", linetype = 'dashed') +
         geom_point()+
         labs(color = 'Severe', #legend_title, 
       x = expression("log"[2]*" (fold change)"), y = expression("-log"[10]*"(p value)")) +
  theme_set(theme_classic(base_size = 10) +
            theme(
              axis.title.y = element_text(face = "bold", margin = margin(0,20,0,0), size = rel(1.1), color = 'black'),
              axis.title.x = element_text(hjust = 0.5, face = "bold", margin = margin(20,0,0,0), size = rel(1.1), color = 'black'),
              plot.title = element_text(hjust = 0.5)
            ))+
    geom_text_repel(max.overlaps = Inf)
```



